# Basic config for experiments
model_type: vit # or cnn
input_channels: 4
num_classes: 1 # binary -> 1 (use BCEWithLogits). For multiclass set >1 and use CrossEntropyLoss
batch_size: 32
epochs: 100
lr: 1e-5
seed: 316
paths:
  train_dir: "/mnt/j/54TB/Jonathan/MSN/train/"
  label_file: "/mnt/j/54TB/Jonathan/MSN/balanced_dataset.txt"
  model_out: "/mnt/j/54TB/Jonathan/MSN/final_cnn_model.pth"
  gradcam_out: "/mnt/j/54TB/Jonathan/MSN/gradcam_outputs"
  nir_csv: "/mnt/j/54TB/Jonathan/MSN/nir_importance_results.csv"

augmentation:
  horizontal_flip: true
  vertical_flip: true
  rotation: 30
  affine: {translate: [0.1,0.1], scale: [0.9,1.1]}


val_split: 0.1
test_split: 0.1
